[package]
name = "kfilter2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.5.31", features = ["derive"] }
kfilter = "0.3.1"
nalgebra = "0.33.2"
plotters = "0.3.7"
rand = "0.9.0"
rand_distr = "0.5.1"
statrs = "0.18.0"
